use brandon_romero;
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('French Marigold',3.99,'flower',8,'../Assets/french_marigold.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Iris',2.99,'flower',5,'../Assets/iris.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Morning Glory',5.99,'flower',7,'../Assets/morning_glory.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Oriental Lily',9.99,'flower',1,'../Assets/oriental_lily.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Pelargonium',12.99,'flower',2,'../Assets/pelargonium.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Tulip',6.99,'flower',15,'../Assets/tulip.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Pink Rose',1.99,'flower',10,'../Assets/rose.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Daisy',2.99,'flower',3,'../Assets/daisy.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Chrysanthemum',19.99,'flower',5,'../Assets/chrysanthemum.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Ageratum Houstonianum',7.13,'flower',3,'../Assets/ageratum_houstoanianum.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Rosemary',1.59,'herb',100,'../Assets/rosemary.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Myrtle',1.99,'herb',40,'../Assets/myrtle.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Oregano',1.59,'herb',12,'../Assets/oregano.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Chives',1.59,'herb',10,'../Assets/chives.jpg');
INSERT INTO product(name,price,category,quantity,product_img) VALUES ('Thyme',1.99,'herb',15,'../Assets/thyme.jpg');